$(document).ready(function(){
    $('#bmenu').click(function(){
    $('#blinks').slideToggle();
    })
    $('#btn-flecha1').click(function(){
        $('#textoPre').slideToggle();
        $('#abajo').toggle();
        $('#arriba').toggle();
        })
    $('#btn-flecha2').click(function(){
        $('#textoPre2').slideToggle();
        $('#abajo2').toggle();
        $('#arriba2').toggle();
        })
    $('#btn-flecha3').click(function(){
        $('#textoPre3').slideToggle();
        $('#abajo3').toggle();
        $('#arriba3').toggle();
        })   
    $('#btn-flecha4').click(function(){
        $('#textoPre4').slideToggle();
        $('#abajo4').toggle();
        $('#arriba4').toggle();
        })   
    $('#btn-flecha5').click(function(){
        $('#textoPre5').slideToggle();
        $('#abajo5').toggle();
        $('#arriba5').toggle();
        })           

})